### ISSUE TITLE
Database Missing

### ISSUE THREAD

**Issue by junkscript** [ssd-tutorials/save-search#1]
Please upload database sql.

**Comment by sebastiansulinski** [comment]
Please check the video for the structure - there's just one table with 6 fields to illustrate the process, but you are most likely going to use your own database - hence exercise files do not contain the sql for the database structure.

**Comment by junkscript** [comment]
Sorry but in your video Save search requests to MySQL database Part 1 of 3 you talk about Remove checkboxes and not about the structure of this database.
I'm not an expert and understand how is create the database for this scritpt is more simple and useful for me. 
Thanks for understanding.

**Comment by sebastiansulinski** [comment]
Apologies @junkscript - you're absolutely right - I've forgotten to add the database file. It is there now so please re-download the files.

**Comment by junkscript** [comment]
Thanks @sebastiansulinski for add database but i think you add the wrong .sql, you add a book table but in the script we talk about id, search and field times for any +1 when search term are the same.
Thanks again :+1:

**Comment by sebastiansulinski** [comment]
There is the `qty` field for that.

**Comment by junkscript** [comment]
OK sorry, i'm talking about this file https://github.com/ssd-tutorials/save-search/blob/master/completed/index.php and i think is more appropriate create packages with correct sql for understanding how this script work. Sorry for disturb you.

**Comment by sebastiansulinski** [comment]
I've added this one for you as well.
